version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      playwright:
        patterns:
          - '@playwright/*'
          - 'playwright*'
          - 'eslint-plugin-playwright'
      eslint:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
          - 'prettier*'
      types:
        patterns:
          - '@types/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
